name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" > azure_secret.txt
          echo "Azure client secret saved."

      - name: Use GH Token
        run: |
          echo "GitHub token is: ${{ secrets.GH_TOKEN }}"


  name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sundayayobami/pfas-msms-tox:latest

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" > azure_secret.txt
          echo "Azure client secret saved."

      - name: Use GH Token
        run: |
          echo "GitHub token is: ${{ secrets.GH_TOKEN }}"
        
